from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.validation import validate_pipeline, write_report  # noqa: E402


def main() -> int:
    before = validate_pipeline(ROOT, ROOT / "scenarios" / "controlled_failure" / "database_pipeline.py")
    after = validate_pipeline(ROOT, ROOT / "src" / "database_pipeline.py")

    metrics_dir = ROOT / "metrics"
    write_report(before, metrics_dir / "before.json")
    write_report(after, metrics_dir / "after.json")
    combined = {"before": before["summary"], "after": after["summary"]}
    (metrics_dir / "before_after.json").write_text(json.dumps(combined, indent=2) + "\n", encoding="utf-8")

    markdown = f"""# Measured before/after results

These values are generated by `python scripts/run_demo.py` against the checked-in reference fixture.

| Metric | Controlled defect | Repaired pipeline |
|---|---:|---:|
| Scientific checks passed | {before['summary']['passed']}/{before['summary']['total']} | {after['summary']['passed']}/{after['summary']['total']} |
| Scientific Contract violations | {before['summary']['contract_violations']} | {after['summary']['contract_violations']} |
| Failed checks | {before['summary']['failed']} | {after['summary']['failed']} |
| Maximum reference error | {before['summary']['max_reference_error_k']:.12g} K | {after['summary']['max_reference_error_k']:.12g} K |

Controlled-defect impact:

- Affected transformations: {', '.join(before['affected_transformations']) or 'none'}
- Affected outputs: {', '.join(before['affected_outputs']) or 'none'}

The detailed, reproducible check results are in `metrics/before.json` and `metrics/after.json`.
"""
    (metrics_dir / "before_after.md").write_text(markdown, encoding="utf-8")

    print(markdown)
    return 0 if after["summary"]["failed"] == 0 and before["summary"]["failed"] > 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
